/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AyahIdRouteImport } from './routes/ayah.$id'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTopicsRouteImport } from './routes/_authenticated/admin/topics'
import { Route as AuthenticatedAdminTafsirsRouteImport } from './routes/_authenticated/admin/tafsirs'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminHadithsRouteImport } from './routes/_authenticated/admin/hadiths'
import { Route as AuthenticatedAdminDuasRouteImport } from './routes/_authenticated/admin/duas'
import { Route as AuthenticatedAdminAyahsRouteImport } from './routes/_authenticated/admin/ayahs'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AyahIdRoute = AyahIdRouteImport.update({
  id: '/ayah/$id',
  path: '/ayah/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTopicsRoute =
  AuthenticatedAdminTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTafsirsRoute =
  AuthenticatedAdminTafsirsRouteImport.update({
    id: '/tafsirs',
    path: '/tafsirs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHadithsRoute =
  AuthenticatedAdminHadithsRouteImport.update({
    id: '/hadiths',
    path: '/hadiths',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDuasRoute = AuthenticatedAdminDuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAyahsRoute = AuthenticatedAdminAyahsRouteImport.update({
  id: '/ayahs',
  path: '/ayahs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/ayah/$id': typeof AyahIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/ayahs': typeof AuthenticatedAdminAyahsRoute
  '/admin/duas': typeof AuthenticatedAdminDuasRoute
  '/admin/hadiths': typeof AuthenticatedAdminHadithsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/tafsirs': typeof AuthenticatedAdminTafsirsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/ayah/$id': typeof AyahIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/ayahs': typeof AuthenticatedAdminAyahsRoute
  '/admin/duas': typeof AuthenticatedAdminDuasRoute
  '/admin/hadiths': typeof AuthenticatedAdminHadithsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/tafsirs': typeof AuthenticatedAdminTafsirsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/ayah/$id': typeof AyahIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/ayahs': typeof AuthenticatedAdminAyahsRoute
  '/_authenticated/admin/duas': typeof AuthenticatedAdminDuasRoute
  '/_authenticated/admin/hadiths': typeof AuthenticatedAdminHadithsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/tafsirs': typeof AuthenticatedAdminTafsirsRoute
  '/_authenticated/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/favorites'
    | '/plans'
    | '/profile'
    | '/search'
    | '/settings'
    | '/topics'
    | '/admin'
    | '/ayah/$id'
    | '/category/$slug'
    | '/topic/$slug'
    | '/admin/audit'
    | '/admin/ayahs'
    | '/admin/duas'
    | '/admin/hadiths'
    | '/admin/import'
    | '/admin/tafsirs'
    | '/admin/topics'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/favorites'
    | '/plans'
    | '/profile'
    | '/search'
    | '/settings'
    | '/topics'
    | '/ayah/$id'
    | '/category/$slug'
    | '/topic/$slug'
    | '/admin/audit'
    | '/admin/ayahs'
    | '/admin/duas'
    | '/admin/hadiths'
    | '/admin/import'
    | '/admin/tafsirs'
    | '/admin/topics'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/favorites'
    | '/plans'
    | '/profile'
    | '/search'
    | '/settings'
    | '/topics'
    | '/_authenticated/admin'
    | '/ayah/$id'
    | '/category/$slug'
    | '/topic/$slug'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/ayahs'
    | '/_authenticated/admin/duas'
    | '/_authenticated/admin/hadiths'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/tafsirs'
    | '/_authenticated/admin/topics'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TopicsRoute: typeof TopicsRoute
  AyahIdRoute: typeof AyahIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  TopicSlugRoute: typeof TopicSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayah/$id': {
      id: '/ayah/$id'
      path: '/ayah/$id'
      fullPath: '/ayah/$id'
      preLoaderRoute: typeof AyahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/topics': {
      id: '/_authenticated/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tafsirs': {
      id: '/_authenticated/admin/tafsirs'
      path: '/tafsirs'
      fullPath: '/admin/tafsirs'
      preLoaderRoute: typeof AuthenticatedAdminTafsirsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hadiths': {
      id: '/_authenticated/admin/hadiths'
      path: '/hadiths'
      fullPath: '/admin/hadiths'
      preLoaderRoute: typeof AuthenticatedAdminHadithsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/duas': {
      id: '/_authenticated/admin/duas'
      path: '/duas'
      fullPath: '/admin/duas'
      preLoaderRoute: typeof AuthenticatedAdminDuasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ayahs': {
      id: '/_authenticated/admin/ayahs'
      path: '/ayahs'
      fullPath: '/admin/ayahs'
      preLoaderRoute: typeof AuthenticatedAdminAyahsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminAyahsRoute: typeof AuthenticatedAdminAyahsRoute
  AuthenticatedAdminDuasRoute: typeof AuthenticatedAdminDuasRoute
  AuthenticatedAdminHadithsRoute: typeof AuthenticatedAdminHadithsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminTafsirsRoute: typeof AuthenticatedAdminTafsirsRoute
  AuthenticatedAdminTopicsRoute: typeof AuthenticatedAdminTopicsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminAyahsRoute: AuthenticatedAdminAyahsRoute,
    AuthenticatedAdminDuasRoute: AuthenticatedAdminDuasRoute,
    AuthenticatedAdminHadithsRoute: AuthenticatedAdminHadithsRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminTafsirsRoute: AuthenticatedAdminTafsirsRoute,
    AuthenticatedAdminTopicsRoute: AuthenticatedAdminTopicsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TopicsRoute: TopicsRoute,
  AyahIdRoute: AyahIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  TopicSlugRoute: TopicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
